INSERT INTO PROPERTY (PROPERTY_ID, NAME, DESCRIPTION, PRICE, PROPERTY_TYPE, STATUS, STATUS_COMMENT, STATUS_DATE, UPDATED_USR_ID, UPDATED_TIMSTM) VALUES
('c73095df-a31d-45a0-8d57-8c43108830c7', 'Old Farm', 'Beautiful Old Farm', '1500.0', 'AGRICULTURE', 'PENDING', 'Just created', '2021-05-20 13:17:07.3', 'khoavu', '2021-05-20 13:17:07.3');

INSERT INTO PROPERTY (PROPERTY_ID, NAME, DESCRIPTION, PRICE, PROPERTY_TYPE, STATUS, STATUS_COMMENT, STATUS_DATE, UPDATED_USR_ID, UPDATED_TIMSTM) VALUES
('d14e8742-cebf-4cf4-b59a-241a25c97f0d', 'Riverside HomeTown', 'FLC Group', '250000.0', 'RESIDENTIAL', 'APPROVED', 'Approved this item', '2021-05-20 13:17:07.3', 'khoavu', '2021-05-20 13:17:07.3');

INSERT INTO API_KEY (ID, KEY) VALUES
('1', '691c5597-e7d2-4c06-af49-f9369b367783');
INSERT INTO API_KEY (ID, KEY) VALUES
('2', '23582a07-6637-4973-ae37-dc8490a4cd6e');
INSERT INTO API_KEY (ID, KEY) VALUES
('3', '23582a07-6637-4973-ae37-dc8490a4cd6e');

INSERT INTO product (id, category, context, description, image, time, title) VALUES
('1', 'Music Rapper','When going to school, there are many subjects; however I still like literature the most. First, literature plays an important role in both education and daily life. Literature is not limit to a subject to be learnt at school. Furthermore, this subject teaches human about several aspects of life. From the very first step, student learns to write, read as well as describe things and people. Moreover, literature teaches one to be a responsible citizen and likeable personality. Literature is more than a subject, it’s an art and it can be applied directly into life such as: journalism, editor. People are not born to learn this unique subject, it needs long time to exercise to master. Besides, when learning literature people not only know more works of art but also understand culture, tradition of each country. Literature is the mirror reflecting human and their lifestyle. Studying literature means learning the way to love and live a true life. All in all, with great benefits of literature, it is necessary for each society especially developing countries.','Write about your favorite subject at school , When going to school, there are many subjects; however I still like literature the most. First, literature plays an important role in both education and daily life. Literature is not limit to a subject to be learnt at school','https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg','2021/06/23','hello mọi người');
INSERT INTO product (id, category, context, description, image, time, title) VALUES
('2', 'Rapper','Each person must have the ideal partner for themselves. For me, my ideal partner is a good heart, honesty, and respect parents, hardworking, and educated. Moreover, she is also a pretty and attractive woman. Firstly, I love my ideal partner very much because she is enough clever to keep my heart cheerful and always helps me when I need her, especially in my studies. Besides that, my girlfriend is good heart and responsible when she always reminds me that education is very important because that is what determines our future. Therefore I have to put my education first and when I have problems in studying, we can share with each other to solve together. Last but not least, my woman always respect my parents by greeting them, asking them whenever she helping them in some situations. For my conclusion, when we want to choose the ideal partner for us, we must know the background of her life and characteristics so that we can choose a suitable lover in the future ','Write about your ideal lover in future ,Each person must have the ideal partner for themselves. For me, my ideal partner is a good heart, honesty, and respect parents, hardworking, and educated. Moreover, she is also a pretty and attractive woman.','https://www.w3schools.com/w3css/img_lights.jpg','26/06/2020','Vi ninh by bắc giang form vietname');
INSERT INTO product (id, category, context, description, image, time, title) VALUES
('3', 'Music','Most of my friends like to stay inside to play video games, read books or watch TV, but I have a good hobby of going outside and playing sports. I play many different sports in my free time; some of them are soccer, swimming, volleyball and basketball. Sometimes I also ride the bikes or do board skating with my cousin in the park. In my opinion, doing sport is one of the rare hobbies that actually have good impacts on me. I am taller than most of my classmates thanks to swimming and basketball lessons that I take during summer time. My muscles are even stronger than my older brother, and I can last longer than most other people in any sport competition. Sports bring me a lot of benefits, and they are also fun things to do at the same time. I love the feeling of the cool water run through my face when I am swimming, and it seems like I am flying whenever I take a dive underwater. When I play soccer, it is very exciting for me or my teammates to score a goal even though we do not take part in any tournament. Both of my physical and mental health become better after I play sports, so it can be considered as the best things to do in my free time. Sports are like a part of my life besides other activities, and I will continue to play sports till I am too weak for them. ','Write about your hobby ,/n Most of my friends like to stay inside to play video games, read books or watch TV, but I have a good hobby of going outside and playing sports','https://cdn.pixabay.com/photo/2021/08/25/20/42/field-6574455__480.jpg','26/06/2019','Vi ninh by bắc giang');
INSERT INTO product (id, category, context, description, image, time, title) VALUES
('4','Young music','I love listening to music, but I’m not too picky in choosing music. I often listen to popular songs or new songs. People call this the Pop genre. Pop music is often the right songs based on different time periods. Therefore, it is difficult to define the specific characteristics of Pop music. Pop songs have simple melodies but are very catchy. And in any country, Pop music has a certain place. The themes of Pop music are also quite diverse, but still mainly revolve around emotional themes. The songs can be quiet and take away the listener’s tears, but sometimes they are also very mischievous and new. It’s also one of the reasons I like pop music. I usually listen to music in my spare time or when I’m not in a good mood. Music helps me dispel feelings of depression. Thanks to music, I feel this life is much more interesting. Sometimes I can find a few friends just because I like the same song. I feel pop music is great','I love listening to music, but I’m not too picky in choosing music. I often listen to popular songs or new songs. People call this the Pop genre','http://tonyenglish.vn/uploads/news/2019/0106/1546787190_Music-music-1440-900.jpg','03/10/2021','Dr.Dre. Rapper Dr.Dre. ...');
INSERT INTO product (id, category, context, description, image, time, title) VALUES
('5','Rapper','I love listening to music, but I’m not too picky in choosing music. I often listen to popular songs or new songs. People call this the Pop genre. Pop music is often the right songs based on different time periods. Therefore, it is difficult to define the specific characteristics of Pop music. Pop songs have simple melodies but are very catchy. And in any country, Pop music has a certain place. The themes of Pop music are also quite diverse, but still mainly revolve around emotional themes. The songs can be quiet and take away the listener’s tears, but sometimes they are also very mischievous and new. It’s also one of the reasons I like pop music. I usually listen to music in my spare time or when I’m not in a good mood. Music helps me dispel feelings of depression. Thanks to music, I feel this life is much more interesting. Sometimes I can find a few friends just because I like the same song. I feel pop music is great.','Everyone has their own favorite genre of music. I have a great passion for rock. In Vietnam, rock is not as popular as in foreign countries. ','https://www.thuthuatweb.net/wp-content/uploads/baiviet//2012/06/music.jpg','01/10/2021','Eminem. rapper Eminem. ...');
INSERT INTO contact (id, email, message, name) VALUES
('1', 'ninhvvph09438@fpt.edu.vn','Student','Vi văn Ninh');

